# fly.toml app configuration file generated for hot-boxed-pie on 2025-10-19T21:29:13-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hot-boxed-pie'
primary_region = 'ord'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
